### ISSUE TITLE
Неточность в условии.

### ISSUE THREAD

**Issue by Saintghetto17** [PeacockTeam/new-job#3]
Здравствуйте, gеречитал условие. Кажется в условии есть неточность. Вы говорите, что две строчки в одной группе, если у них есть совпадение в одной из колонок. Но тогда пример трех строчек не подходит, так как 1 и 3 не имеют одинаковых значений в колонках. Получается ,что это должно выполняться не попарно? Значит важен порядок добавления и, чтобы у СОСЕДЕЙ были пересечения по колонкам?

**Comment by disovi** [comment]
добрый день, 1 и 2 находятся в одной группе по пересечению, 2 и 3 тоже. 1 и 3 попадают в эту группу, тк обе пересекаются со 2й. Каждая строчка может состоять только в одной группе.

**Comment by Saintghetto17** [comment]
Спасибо, понял. Значит важна лишь транзитивность
